# Generated by Django 5.2.1 on 2025-06-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_q_s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Q_S',
            new_name='members_q_a',
        ),
        migrations.DeleteModel(
            name='Q_A',
        ),
    ]
